# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Build and Render
        shell: bash
        run: |
          npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_GA_TRACKING_ID: G-M6H0YTT6ND  # Google Analytics tracking ID

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: "out"  # Ensure 'out' is the correct directory for your static files
          name: github-pages  # Artifact name

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages  # Ensure this matches the artifact name
